// Copyright 2020-2021, University of Colorado Boulder

/**
 * Auto-generated from modulify, DO NOT manually modify.
 */
/* eslint-disable */
import getStringModule from '../../chipper/js/getStringModule.js';
import shred from './shred.js';

type StringsType = {
  'protonsColon': string,
  'neutronsColon': string,
  'electronsColon': string,
  'hydrogen': string,
  'helium': string,
  'lithium': string,
  'beryllium': string,
  'boron': string,
  'carbon': string,
  'nitrogen': string,
  'oxygen': string,
  'fluorine': string,
  'neon': string,
  'sodium': string,
  'magnesium': string,
  'aluminum': string,
  'silicon': string,
  'phosphorus': string,
  'sulfur': string,
  'chlorine': string,
  'argon': string,
  'potassium': string,
  'calcium': string,
  'scandium': string,
  'titanium': string,
  'vanadium': string,
  'chromium': string,
  'manganese': string,
  'iron': string,
  'cobalt': string,
  'nickel': string,
  'copper': string,
  'zinc': string,
  'gallium': string,
  'germanium': string,
  'arsenic': string,
  'selenium': string,
  'bromine': string,
  'krypton': string,
  'rubidium': string,
  'strontium': string,
  'yttrium': string,
  'zirconium': string,
  'niobium': string,
  'molybdenum': string,
  'technetium': string,
  'ruthenium': string,
  'rhodium': string,
  'palladium': string,
  'silver': string,
  'cadmium': string,
  'indium': string,
  'tin': string,
  'antimony': string,
  'tellurium': string,
  'iodine': string,
  'xenon': string,
  'cesium': string,
  'barium': string,
  'lanthanum': string,
  'cerium': string,
  'praseodymium': string,
  'neodymium': string,
  'promethium': string,
  'samarium': string,
  'europium': string,
  'gadolinium': string,
  'terbium': string,
  'dysprosium': string,
  'holmium': string,
  'erbium': string,
  'thulium': string,
  'ytterbium': string,
  'lutetium': string,
  'hafnium': string,
  'tantalum': string,
  'tungsten': string,
  'rhenium': string,
  'osmium': string,
  'iridium': string,
  'platinum': string,
  'gold': string,
  'mercury': string,
  'thallium': string,
  'lead': string,
  'bismuth': string,
  'polonium': string,
  'astatine': string,
  'radon': string,
  'francium': string,
  'radium': string,
  'actinium': string,
  'thorium': string,
  'protactinium': string,
  'uranium': string,
  'neptunium': string,
  'plutonium': string,
  'americium': string,
  'curium': string,
  'berkelium': string,
  'californium': string,
  'einsteinium': string,
  'fermium': string,
  'mendelevium': string,
  'nobelium': string,
  'lawrencium': string,
  'rutherfordium': string,
  'dubnium': string,
  'seaborgium': string,
  'bohrium': string,
  'hassium': string,
  'meitnerium': string,
  'darmstadtium': string,
  'roentgenium': string,
  'copernicium': string,
  'nihonium': string,
  'flerovium': string,
  'moscovium': string,
  'livermorium': string,
  'tennessine': string,
  'oganesson': string,
  'minusSignIon': string,
  'neutralAtom': string,
  'positiveSignIon': string,
  'stable': string,
  'unstable': string,
  'periodicTable': string
};

const shredStrings = getStringModule( 'SHRED' ) as StringsType;

shred.register( 'shredStrings', shredStrings );

export default shredStrings;
